### ISSUE TITLE
Feat: Add batch {enabled: true/false} option for job launch command

### ISSUE THREAD

**Issue by cgpu** [lifebit-ai/cloudos-py#26]
https://github.com/lifebit-ai/cloudos-py/blob/1e15741b587cbdf5eed748ea073506d041b5422d/cloudos/jobs/job.py#L123

```diff
+ resumable, 
+ batch {enabled: batch_boolean_flag} 
```

This addition will enable the user to select if the job will run with `ignite` (`batch {enabled: false}`) or AWS Batch (`batch {enabled: true}`)

**Comment by dapineyro** [comment]
Addressed by https://github.com/lifebit-ai/cloudos-py/pull/28
